### 붓꽃의 품종 분류하기
#### 가설
#### 학습과 분류의 종류(회귀 x, 분류, 지도학습)

In [ ]:
from sklearn.datasets import load_iris
iris_dataset = load_iris() # Python의 dict와 비슷한 유사한 Bunch Class의 객체로 되어있다.

In [ ]:
# iris_dataset의 Key 확인하기
iris_dataset.keys()    

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [7]:
iris_dataset['data'][:10]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [9]:
iris_dataset['target']

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [10]:
iris_dataset['target_names']

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [13]:
# array는 섞어쓸 수 없다
# df는 섞어쓸 수 있다

print(iris_dataset['DESCR'])

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

:Number of Instances: 150 (50 in each of three classes)
:Number of Attributes: 4 numeric, predictive attributes and the class
:Attribute Information:
    - sepal length in cm
    - sepal width in cm
    - petal length in cm
    - petal width in cm
    - class:
            - Iris-Setosa
            - Iris-Versicolour
            - Iris-Virginica

:Summary Statistics:

============== ==== ==== ======= ===== ====================
                Min  Max   Mean    SD   Class Correlation
============== ==== ==== ======= ===== ====================
sepal length:   4.3  7.9   5.84   0.83    0.7826
sepal width:    2.0  4.4   3.05   0.43   -0.4194
petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
============== ==== ==== ======= ===== ====================

:Missing Attribute Values: None
:Class Distribution: 33.3% for each of 3 classes.
:Cr

In [15]:
iris_dataset['feature_names']

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [16]:
iris_dataset['data'].shape

(150, 4)

### Train과 Test Data 분리하기

In [19]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
import collections # 빈도수 세기

In [22]:
X_train, X_test, y_train, y_test = \
  train_test_split(
    iris_dataset['data'],
    iris_dataset['target'],
    random_state=42,
    stratify=iris_dataset['target'],
    test_size=0.2
  )

In [24]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)


(120, 4)
(120,)
(30, 4)
(30,)


### kNN으로 학습 하여 정확도 구하기
- n_neighbors = 1
- test의 예측값 출력
- y와 y^의 정확도 출력

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

kn = KNeighborsClassifier(n_neighbors=1)
kn.fit(X_train, y_train)
print("Train score:", kn.score(X_train, y_train))
print("Test score:", kn.score(X_test, y_test))
kn.score

Train score: 1.0
Test score: 0.9666666666666667


<bound method ClassifierMixin.score of KNeighborsClassifier(n_neighbors=1)>

In [ ]:
# 예측값을 구하기
pred = kn.predict(X_test)
pred

array([0, 2, 1, 1, 0, 1, 0, 0, 2, 1, 2, 2, 2, 1, 0, 0, 0, 1, 1, 1, 0, 2,
       1, 2, 2, 1, 1, 0, 2, 0])

In [ ]:
# 예측값과 실제 test target과 동일한 데이터의 평균이 정확도와 일치하는지 확인
(pred == y_test).mean()

0.9666666666666667