### Numpy

In [2]:
import numpy as np

In [3]:
# List로 만들기
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [4]:
# 배열의 갯수
len(arr1)

5

In [5]:
arr1.shape

(5,)

In [7]:
data2 = [
  [1,2,3,4],
  [5,6,7,8]
]
arr1 = np.array(data2)
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [8]:
arr1.shape

(2, 4)

In [9]:
# 0으로 구성된 1차원 array 생성
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [10]:
# 1로 구성된 1차원 array 생성
np.ones(5)

array([1., 1., 1., 1., 1.])

In [13]:
# 특정숫자로 구성된 1차원 array생성
np.full(5, 10.0)

array([10., 10., 10., 10., 10.])

In [18]:
# 동영상 : 1초, 30fps, 1920 X 1080
np.zeros((30, 3, 1920, 1080)).shape

(30, 3, 1920, 1080)

---
### 연산

In [21]:
arr1 = np.array(
  [
    [1,2,3],
    [4,5,6]
  ]
)
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
arr2 = np.array(
  [
    [7,8,9],
    [10,11,12]
  ]
)
arr2

array([[ 7,  8,  9],
       [10, 11, 12]])

In [25]:
arr1 * arr2

array([[ 7, 16, 27],
       [40, 55, 72]])

In [26]:
arr1 * 2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [28]:
# arr1의 제곱근 구하기

np.sqrt(arr1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

### Data handling

In [29]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
arr[5]

5

In [34]:
# arr의 처음부터 4번 index의 데이터 불러오기
arr[:4+1]

array([0, 1, 2, 3, 4])

### 2차원 배열

In [35]:
arr2d = np.array(
  [
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]
  ]
)
arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [37]:
arr2d[2]

array([ 9, 10, 11, 12])

In [43]:
arr2d[1:2+1]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [54]:
arr2d[:,3]

array([ 4,  8, 12, 16])

In [52]:
arr2d[:,[0,1]]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]])

In [55]:
arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [68]:
# arr2d[0,1] = 0
# arr2d[0,2] = 0
# arr2d[1,1] = 0
# arr2d[1,2] = 0


arr2d[:1+1,1:2+1] = 0

arr2d

array([[ 1,  0,  0,  4],
       [ 5,  0,  0,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

---
###  배열 차원 변경

In [69]:
arr = np.arange(1, 8+1, 1)
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [71]:
# 2차원 배열로 변경
arr1 = np.reshape(arr, (2,4))
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [72]:
# arr을 3차원 배열로 변경
arr2 = np.reshape(arr, (2,2,2))
arr2

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])