### 파이썬 List

In [2]:
my_list = [10, "abc", 20.1, True]
print(my_list)
my_list[1]

[10, 'abc', 20.1, True]


'abc'

In [ ]:
my_list2 = [
  [10, 20, 30],
  [40 ,50 ,60],
]
print(my_list2)
my_list2[1][1] # 행, 열 순서

[[10, 20, 30], [40, 50, 60]]


50

### Numpy
#### 배열 생성 및 기초
: 딥러닝에서 배열의 기본이 되는 ndarray 사용법

In [6]:
import numpy as np

In [8]:
# 1차원 배열
arr1 = np.array(
  [1,2,3]
)
arr1

array([1, 2, 3])

In [9]:
# 2차원 배열
my_arr = np.array(
  [
    [10,20,30],
    [40,50,60]
  ]
)
my_arr

array([[10, 20, 30],
       [40, 50, 60]])

In [12]:
my_arr[0][2]
my_arr[0,2]


30

In [13]:
# Numpy 내장 함수
np.sum(my_arr)

210

In [18]:
# 특정 값으로 초기화
np.zeros(3)
np.zeros((2,3))
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [21]:
np.ones((3,3)) * 255

array([[255., 255., 255.],
       [255., 255., 255.],
       [255., 255., 255.]])

In [ ]:
np.full((2,2), 255) ## 255는 데이터, 2,2는 어레이

array([[255, 255],
       [255, 255]])

In [ ]:
# 단위 행렬 - 희소행렬 - 원핫인코딩
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [24]:
np.arange(0,10,1.5)

array([0. , 1.5, 3. , 4.5, 6. , 7.5, 9. ])

In [25]:
# 0~1범위에서 5개 값 균등 분할
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

### 배열 속성 및 변형

In [27]:
my_arr

array([[10, 20, 30],
       [40, 50, 60]])

In [ ]:
# 형태(크기) ## 2행 3열이구나
my_arr.shape

(2, 3)

In [ ]:
# 차원수 ## 2차원 데이터구나
my_arr.ndim

2

In [ ]:
# 데이터 타입 # int64구나
my_arr.dtype

dtype('int64')

In [ ]:
# 전체 data 갯수 # 6개 데이터를 가지고 있구나
my_arr.size

6

In [33]:
# 차원 변경 (2X3 -> 3X2)
my_arr.reshape(3,2)

array([[10, 20],
       [30, 40],
       [50, 60]])

In [34]:
my_arr.T

array([[10, 40],
       [20, 50],
       [30, 60]])

### indexing과 slicing
: 배열에서 원하는 값 선택, Masking, 조건처리

In [35]:
my_arr

array([[10, 20, 30],
       [40, 50, 60]])

In [44]:
print(my_arr[0]) # 0번 행이 나옴
print(my_arr[1])
print(my_arr[1:]) # : 은 차원이 들어간다. 속성값이 들어가는 것이다.
print(my_arr[0:1]) # 1 전까지 차원을 늘려라
print(my_arr[:,1]) # 범위를 쓰지 않았다. 차원을 가져오지 않는다.
print(my_arr[1:,::2]) # step 처음부터 2칸 증가
my_arr[my_arr > 40]

[10 20 30]
[40 50 60]
[[40 50 60]]
[[10 20 30]]
[20 50]
[[40 60]]


array([50, 60])

In [47]:
my_arr > 40

array([[False, False, False],
       [False,  True,  True]])

In [48]:
my_arr[my_arr > 40]

array([50, 60])

In [ ]:
# 1차원으로 평탄화(Flatten) 한다.
my_arr2 = my_arr.reshape(-1, 1) # 행은 니가 알아서하고, 열 1개짜리 만들어줘
print(my_arr2) # 대괄호가 아니라 컴마의 유무를 봐라
print(my_arr2.shape)

my_arr3 = my_arr.ravel()
print(my_arr3) # 컴마가 없어
print(my_arr3.shape) # 0차원이야

[[10]
 [20]
 [30]
 [40]
 [50]
 [60]]
(6, 1)
[10 20 30 40 50 60]
(6,)


In [ ]:
a = 1,
a
# 딥러닝에서는 이렇게 튜플로 써줄 필요가 있다.

(1,)

### BroadCasting
: 서로 다른 차원의 배열간 연산을 가능하게 함
- 두 배열의 차원수를 오른쪽(행, 열)에서 부터 비교
 - 각 차원의 크기가 일치하거나, 열이 1이면(1차원데이터) 연산 가능하고 그렇지 않으면 오류 발생

In [57]:
# 각 차원의 크기가 일치하는 덧셈
arr1 = np.array(
  [
    [1,1,1],
    [2,2,2],
    [3,3,3]
  ]
)
arr1

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [58]:
# 각 차원의 크기가 일치하는 덧셈
arr2 = np.array(
  [
    [10,10,10],
    [20,20,20],
    [30,30,30]
  ]
)
arr2

array([[10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [59]:
arr1 + arr2

array([[11, 11, 11],
       [22, 22, 22],
       [33, 33, 33]])

In [61]:
# 각 차원의 크기가 일치하지 않거나 각 차원 중 한개의 차원이 1인 경우
arr1 = np.array(
  [
    [1],
    [2],
    [3]
  ]
)

print(arr1)
print(arr1.shape)

[[1]
 [2]
 [3]]
(3, 1)


In [ ]:
arr2 = np.array(
    [10,20,30]
)
print(arr2)
print(arr2.shape)

[10 20 30]
(3,)


In [65]:
print(arr1+arr2)
print(arr2+arr1)

[[11 21 31]
 [12 22 32]
 [13 23 33]]
[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [67]:
# 안되는 경우
arr1 = np.array(
  [
    [1,2,3],
    [4,5,6]
  ]
)


arr2 = np.array(
    [10,20]
)

try: 
  arr1 + arr2
except ValueError as e:
  print("Error :", e)

Error : operands could not be broadcast together with shapes (2,3) (2,) 


### 벡터 / 행렬 연산
: 딥러닝에서 가중치 계산, loss(손실함수), gradient(가중치)등에 필수

In [71]:
arr1 = np.array(
  [10,20,30]
)
print(arr1.shape)
print(arr1)

(3,)
[10 20 30]


In [72]:
arr2 = np.array(
  [
    [1],
    [2],
    [3]
  ]
)
print(arr2.shape)
print(arr2)

(3, 1)
[[1]
 [2]
 [3]]


In [74]:
arr1 + arr2
np.add(arr1, arr2)

array([[11, 21, 31],
       [12, 22, 32],
       [13, 23, 33]])

In [78]:
arr1 - arr2
np.subtract(arr1,arr2)

array([[ 9, 19, 29],
       [ 8, 18, 28],
       [ 7, 17, 27]])

In [80]:
arr1 * arr2
np.multiply(arr1, arr2)

array([[10, 20, 30],
       [20, 40, 60],
       [30, 60, 90]])

In [82]:
arr1/ arr2
np.divide(arr1, arr2)

array([[10.        , 20.        , 30.        ],
       [ 5.        , 10.        , 15.        ],
       [ 3.33333333,  6.66666667, 10.        ]])

In [ ]:
# 행렬곱 연산
np.matmul(arr1, arr2)

array([140])

In [84]:
(10*1) + (20*2) + (30*3)

140

In [85]:
# Python 3.5 이상
arr1 @ arr2

array([140])

### 통계 및 수학 함수
: 손실계산, 평균, 분산, 정규화 등에 사용

In [86]:
arr1

array([10, 20, 30])

In [87]:
# 평균
np.mean(arr1)

20.0

In [88]:
# 표준편차
np.std(arr1)

8.16496580927726

In [89]:
# 분산
np.var(arr1)

66.66666666666667

In [90]:
# 합계
np.sum(arr1)

60

In [122]:
arr3 = arr1 * arr2
arr3

array([[10, 20, 30],
       [20, 40, 60],
       [30, 60, 90]])

In [99]:
arr3.shape

(3, 3)

In [100]:
# 행간의 합계
np.sum(arr3, axis=0) # row가 0번이니까.

array([36, 66, 96])

In [101]:
# 열간의 합계
np.sum(arr3, axis=1)

array([63, 66, 69])

In [102]:
# 전체 합계
np.sum(arr3)
np.sum(arr3, axis=(0,1))

198

### 난수 생성
: 신경망 weight의 초기화, 데이터 섞기 등에서 사용

In [103]:
# 재현 가능성 정의
np.random.seed(42)

In [104]:
# 0~1 균등 분포
np.random.rand(3,2)

array([[0.37454012, 0.95071431],
       [0.73199394, 0.59865848],
       [0.15601864, 0.15599452]])

In [105]:
# 평균이 0이고 분산 1인 정규분포
np.random.randn(3,2)

array([[ 1.57921282,  0.76743473],
       [-0.46947439,  0.54256004],
       [-0.46341769, -0.46572975]])

In [106]:
# 정수의 랜덤
np.random.randint(0,10,(3,2))

array([[9, 5],
       [8, 0],
       [9, 2]])

In [114]:
# shuffle
np.random.permutation(10)

array([6, 2, 5, 8, 3, 0, 9, 7, 4, 1])

### 조건 및 논리 연산
: 데이터 전처리, 마스킹 처리 등에 활용

In [117]:
arr1 > 20

array([False, False,  True])

In [118]:
# 조건에 따라 선택
np.where(arr1 > 20, 1, 0)

array([0, 0, 1])

In [119]:
# 하나라도 참이면 True
np.any(arr1 > 20)

True

In [120]:
# 모두가 참일때만 True
np.all(arr1 > 20)

False

### 데이터 추가

In [123]:
arr3

array([[10, 20, 30],
       [20, 40, 60],
       [30, 60, 90]])

In [124]:
# 행간으로 데이터 추가하기

np.concatenate([arr3, arr3], axis=0)

array([[10, 20, 30],
       [20, 40, 60],
       [30, 60, 90],
       [10, 20, 30],
       [20, 40, 60],
       [30, 60, 90]])

In [125]:
# 열간으로 데이터 추가하기

np.concatenate([arr3, arr3], axis=1)

array([[10, 20, 30, 10, 20, 30],
       [20, 40, 60, 20, 40, 60],
       [30, 60, 90, 30, 60, 90]])

In [126]:
np.column_stack([arr3,arr3])

array([[10, 20, 30, 10, 20, 30],
       [20, 40, 60, 20, 40, 60],
       [30, 60, 90, 30, 60, 90]])

In [127]:
np.row_stack([arr3,arr3])

array([[10, 20, 30],
       [20, 40, 60],
       [30, 60, 90],
       [10, 20, 30],
       [20, 40, 60],
       [30, 60, 90]])

---
### Map

In [129]:
numbers = [1,2,3,4,5]
# 각 요소를 제공하는 함수
def square(n):
  return n**2

list(map(square, numbers))

[1, 4, 9, 16, 25]

In [131]:
numbers = [1,2,3,4,5]
list(map(lambda n: n**2, numbers))


[1, 4, 9, 16, 25]

In [134]:
# 여러 리스트를 동시에 변환
# 결과 = [5,7,9]

list1 = [1,2,3]
list2 = [4,5,6]

list(map(lambda n1,n2: n1+n2, list1,list2))

[5, 7, 9]

In [135]:
numbers = [1,2,3,4,5]
# 결과 ['홀수', '짝수', ...]

list(map(lambda n: "짝수" if n % 2 == 0 else "홀수", numbers))

['홀수', '짝수', '홀수', '짝수', '홀수']